// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CountLikesByPost(ctx context.Context, postID int64) ([]int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateFollow(ctx context.Context, arg CreateFollowParams) error
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, commentID int64) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeletePost(ctx context.Context, postID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetPostByID(ctx context.Context, postID int64) (Post, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	ListCommentsByPost(ctx context.Context, postID int64) ([]Comment, error)
	ListFollowers(ctx context.Context, followingID int64) ([]ListFollowersRow, error)
	ListFollowing(ctx context.Context, followerID int64) ([]ListFollowingRow, error)
	ListPostsByUser(ctx context.Context, userID int64) ([]Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
