// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rpc_create_post.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*CreatePostRequest_Metadata
	//	*CreatePostRequest_Chunk
	Data          isCreatePostRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_rpc_create_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_post_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetData() isCreatePostRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreatePostRequest) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Data.(*CreatePostRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *CreatePostRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Data.(*CreatePostRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isCreatePostRequest_Data interface {
	isCreatePostRequest_Data()
}

type CreatePostRequest_Metadata struct {
	// Metadata must be sent as the first message.
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type CreatePostRequest_Chunk struct {
	// Subsequent messages contain chunks of file data.
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*CreatePostRequest_Metadata) isCreatePostRequest_Data() {}

func (*CreatePostRequest_Chunk) isCreatePostRequest_Data() {}

// Metadata about the post and file.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_rpc_create_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_rpc_create_post_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Metadata) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *Metadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Metadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// A chunk of file data.
type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_rpc_create_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_rpc_create_post_proto_rawDescGZIP(), []int{2}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_rpc_create_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_post_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

var File_rpc_create_post_proto protoreflect.FileDescriptor

const file_rpc_create_post_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_create_post.proto\x12\x02pb\x1a\n" +
	"post.proto\"n\n" +
	"\x11CreatePostRequest\x12*\n" +
	"\bmetadata\x18\x01 \x01(\v2\f.pb.MetadataH\x00R\bmetadata\x12%\n" +
	"\x05chunk\x18\x02 \x01(\v2\r.pb.FileChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"}\n" +
	"\bMetadata\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"%\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"2\n" +
	"\x12CreatePostResponse\x12\x1c\n" +
	"\x04post\x18\x01 \x01(\v2\b.pb.PostR\x04postB\x19Z\x17github.com/insta-app/pbb\x06proto3"

var (
	file_rpc_create_post_proto_rawDescOnce sync.Once
	file_rpc_create_post_proto_rawDescData []byte
)

func file_rpc_create_post_proto_rawDescGZIP() []byte {
	file_rpc_create_post_proto_rawDescOnce.Do(func() {
		file_rpc_create_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_post_proto_rawDesc), len(file_rpc_create_post_proto_rawDesc)))
	})
	return file_rpc_create_post_proto_rawDescData
}

var file_rpc_create_post_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_create_post_proto_goTypes = []any{
	(*CreatePostRequest)(nil),  // 0: pb.CreatePostRequest
	(*Metadata)(nil),           // 1: pb.Metadata
	(*FileChunk)(nil),          // 2: pb.FileChunk
	(*CreatePostResponse)(nil), // 3: pb.CreatePostResponse
	(*Post)(nil),               // 4: pb.Post
}
var file_rpc_create_post_proto_depIdxs = []int32{
	1, // 0: pb.CreatePostRequest.metadata:type_name -> pb.Metadata
	2, // 1: pb.CreatePostRequest.chunk:type_name -> pb.FileChunk
	4, // 2: pb.CreatePostResponse.post:type_name -> pb.Post
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_create_post_proto_init() }
func file_rpc_create_post_proto_init() {
	if File_rpc_create_post_proto != nil {
		return
	}
	file_post_proto_init()
	file_rpc_create_post_proto_msgTypes[0].OneofWrappers = []any{
		(*CreatePostRequest_Metadata)(nil),
		(*CreatePostRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_post_proto_rawDesc), len(file_rpc_create_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_post_proto_goTypes,
		DependencyIndexes: file_rpc_create_post_proto_depIdxs,
		MessageInfos:      file_rpc_create_post_proto_msgTypes,
	}.Build()
	File_rpc_create_post_proto = out.File
	file_rpc_create_post_proto_goTypes = nil
	file_rpc_create_post_proto_depIdxs = nil
}
